scrapez/ui/__init__.py
from flask_sslify import SSLify
from flask import Flask
from config import config
from ..utils import register_blueprints, register_extensions
import os

def create_app(profile=None, ssl=False):
    if profile is None:
        profile = os.environ.get('PROFILE', 'default')
    cfg = config[profile]
    app = Flask(__name__)
    if ssl:
        SSLify(app)
    app.config.from_object(cfg)
    app.url_map.strict_slashes = False

    from blueprints import BLUEPRINTS
    register_blueprints(app, BLUEPRINTS)

    from extensions import EXTENSIONS
    register_extensions(app, EXTENSIONS)

    return app

scrapez/ui/app.py
from . import create_app

app = create_app()

scrapez/ui/blueprints.py
from home import home as home_bp
from links import links as links_bp
from videos import videos as videos_bp
from downloads import downloads as downloads_bp
from chat import chat as chat_bp

BLUEPRINTS = [
    (home_bp, '/'),
    (links_bp, '/links'),
    (videos_bp, '/videos'),
    (downloads_bp, '/downloads'),
    (chat_bp, '/chat'),
]

scrapez/ui/chat/__init__.py
from flask import Blueprint

chat = Blueprint('chat', __name__)

import routes, events

scrapez/ui/chat/routes.py
from flask import render_template
from . import chat

@chat.route('/')
def index():
    return render_template('chat.html')

scrapez/ui/downloads/__init__.py
from flask import Blueprint

downloads = Blueprint('downloads', __name__)

import routes, events

scrapez/ui/downloads/routes.py
from . import downloads
from flask import send_from_directory, current_app as app, url_for, jsonify, render_template
import os

EXTENSIONS_WHITELIST = [
    'mp4',
    'avi',
    'pdf'
]
EXTENSIONS_BLACKLIST = [
    'exe',
    'sh',
    'o',
    'dll',\
    'torrent'
]

@downloads.route('/')
def index():
    return render_template('downloads.html')

@downloads.route('/<path:filename>')
def send_file(filename):
    return send_from_directory(app.config['DOWNLOAD_FOLDER'], filename)

@downloads.route('/list')
def list_downloads():
    items = []
    for filename in os.listdir(app.config['DOWNLOAD_FOLDER']):
        extension = filename.split('.')[-1]
        if extension in ['mp4', 'avi']:
            path = os.path.join(app.config['DOWNLOAD_FOLDER'], filename)
            download_url = url_for('downloads.send_file', filename=filename)
            item = {
                'filename': filename,
                'download_url': download_url
            }
            items.append(item)
    return jsonify({
        'downloads': items
    })

scrapez/ui/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

import routes

scrapez/ui/home/routes.py
from . import home
from ...utils import get_dir_tree
from flask import render_template, jsonify, request, current_app as app
from celery.result import AsyncResult
import pprint, logging

log = logging.getLogger(__name__)

@home.route('/')
def index():
    return render_template('home.html')

@home.route('/query', methods=['POST'])
def query():
    from scrape import scrape_files
    log.info("-> Received query")
    url_data = request.get_json()
    log.info("-> Query data: %s" % pprint.pformat(url_data))
    if not url_data:
        return jsonify({
            'message': 'No URL data'
        })
    if 'name' not in url_data:
        url_data['name'] = url_data['url']
    if 'recurse' not in url_data:
        url_data['recurse'] = True
    if 'subfolders' not in url_data:
        url_data['subfolders'] = True
    url_data['extensions'] = url_data['extensions'].split(',')
    log.info("-> Creating Celery task ...")
    r = scrape_files.delay([url_data], app.conf['DOWNLOAD_FOLDER'])
    msg = "Task '%s' created" % r.id
    log.info("-> " + msg)
    resp = {
        'message': msg,
        'id': r.id
    }
    log.debug(resp)
    return jsonify(resp)

@home.route('/list', methods=['GET'])
def list_files():
    files = get_dir_tree(app.conf['DOWNLOAD_FOLDER'])
    log.info(pprint.pformat(files))
    return jsonify(files)

# @files.route('/task/<id>')
# def task_info(id):
#     res = AsyncResult(id)
#     log.info("-> Polling task: %s" % res)
#     resp = {
#         'result': None,
#         # 'ready': res.ready(),
#         'status': res.status,
#         'id': res.task_id
#     }
#     if res.ready():
#         resp['result'] = res.get()
#     return jsonify(resp)

scrapez/ui/links/__init__.py
from flask import Blueprint

links = Blueprint('links', __name__)

import routes

scrapez/ui/links/routes.py
from flask import render_template
from . import links

@links.route('/')
def index():
    return render_template('links.html')

scrapez/ui/videos/__init__.py
from flask import Blueprint

videos = Blueprint('videos', __name__)

import routes, events

scrapez/ui/videos/routes.py
from flask import render_template, request, jsonify, current_app as app
from . import videos
from pytube import YouTube
from tasks.youtube import download as download_yt, \
                          list_streams as list_yt_streams, \
                          search as search_yt

@videos.route('/')
def index():
    return render_template('videos.html')

@videos.route('/youtube/search')
def search_youtube():
    query = request.args['query']
    data = search_yt(query, async=True, events=True)
    return jsonify(data)

@videos.route('/youtube/list')
def list_youtube_streams():
    url = request.args['url']
    data = list_yt_streams(url, events=True)
    return jsonify(data)

@videos.route('/youtube/download')
def download_youtube():
    url = request.args['url']
    itag = request.args['itag'].rstrip(',')
    app.logger.info("Downloading %s with itag %s" % (url, itag))
    print("Downloading %s with itag %s" % (url, itag))
    # print("Download folder: %s" % app.config['DOWNLOAD_FOLDER'])
    try:
        res = download_yt.delay(url, itag, output_path=app.config['DOWNLOAD_FOLDER'], api=True, events=True)
        return jsonify({
            'success': True,
            'message': 'Your video is downloading',
            'id': res.id
            # 'output_path': app.config['DOWNLOAD_FOLDER']
        })
    except Exception as e:
        return jsonify({
            'success': False,
            'exception_class': type(e).__name__,
            'exception_str': str(e)
        })

scrapez/ui/templates/chat.html
{% extends 'layout.html' %}

{% block js_assets %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.5/jstree.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js"></script>
  <script src="{{ url_for('static', filename='js/chat_events.js') }}"></script>
{% endblock %}

{% block body %}
  <div class='ui segment' id='flask_chat'>
    <div class='ui header'>Chat</div>
    <p>Pas de conneries !</p>
    <textarea readonly id="chat" class='ui segment' cols="80" rows="15"></textarea><br><br>
    <div class='ui input'>
      <input id="name" placeholder="Enter your name"><div id='rename' class='ui basic button'>Set name</div></br></br>
    </div>
    </br>
    <div class='ui input'>
      <input id="text" size="80" placeholder="Enter your message here ..."><br><br>
    </div>
  </div>
{% endblock %}

scrapez/ui/templates/downloads.html
{% extends 'layout.html' %}

{% block css_assets %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.css"/>
{% endblock %}

{% block js_assets %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.5/jstree.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js"></script>
  <script src="{{ url_for('static', filename='js/download_events.js') }}"></script>
{% endblock %}

{% block body %}
  <div class='ui segment'>
    <div class='ui input'>
      <input id='search' placeholder="Search for download ..."></input>
    </div>
    <button class='ui button' id='query'><i class='ui search icon'></i>Search</button>
    </br></br>
  </div>
  <div class='ui segment'>
    <div id='results_header'>
      <div class='ui header'>Results</div>
      <p data-number=0 id='nresults'>No results found.</p>
    </div>
    <div id='loader' width="50%" class="ui icon message">
      <i class="notched circle loading icon"></i>
      <div class="content">
        <div class="header">
          Searching for downloads ...
        </div>
        <p>We're looking on the local hard drive for some content.</p>
      </div>
    </div>
    <div id='results' class="ui padded celled list">
    </div>
  </div>
{% endblock %}

scrapez/ui/templates/home.html
{% extends "layout.html" %}

{% block css_assets %}
  <link href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.5/themes/default/style.min.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block js_assets %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.5/jstree.min.js"></script>
  <script src="{{ url_for('static', filename='js/home_events.js') }}"></script>
{% endblock %}

{% block body %}
  <div class='ui segment'>
    <div class='ui input'>
      <input id='search' placeholder="Enter URL ..."></input>
    </div>
    <div class='ui input'>
      <input id='extensions' placeholder="Enter extensions (pdf, csv, doc, ...)"></input>
    </div>
    <button class='ui button' id='query'>Scrape!</button>
    </br></br>
    <div class='ui checkbox'>
      <input id='authenticate' type='checkbox'></input>
      <label>Authenticate</label>
    </div>
    </br>
    <div style='display:none' id='auth'>
      <div class='ui tiny input'>
        <input id='username' placeholder='Enter username ...'></input>
      </div>
      <div class='ui tiny input'>
        <input id='password' type='password' placeholder='Enter password ...'></input>
      </div>
      </br></br>
    </div>
    <div class='ui checkbox'>
      <input id='recurse' type='checkbox'></input>
      <label>Recurse</label>
    </div>
    </br>
    <div class='ui tiny input'>
      <input style="display:none" id='recurse_depth' placeholder='Recurse depth ...'></input>
    </div>
  </div>
  <div class='ui segment' id='results'></div>
  <div class='ui segment' id='jstree'></div>
{% endblock %}

scrapez/ui/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>ScrapEZ</title>
    {{ JSGlue.include() }}
    {% block css_core_assets %}
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.css"/>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"/>
    {% endblock %}
    {% block css_assets %} <!-- Override in other templates --> {% endblock %}
  </head>
  <body>
    <div class='ui padded container'>
      </br>
      {% include "navbar.html" %}
      {% block body %} <!-- Override in other templates --> {% endblock %}
    </div>
    {% block js_core_assets %}
      <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.bundle.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js"></script>
      <script src="{{ url_for('static', filename='js/shared.js') }}"></script>
    {% endblock %}
    {% block js_assets %} <!-- Override in other templates --> {% endblock %}
  </body>
</html>

scrapez/ui/templates/links.html
{% extends "layout.html" %}

{% block css_assets %}
{% endblock %}

{% block js_assets %}
{% endblock %}

{% block body %}
{% endblock %}

scrapez/ui/templates/navbar.html
<div style="padding:10px" class='ui segment'>
  <nav style="padding:0px" class="navbar navbar-expand-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <h1 style="margin-top:0px" class="navbar-brand mb-0">ScrapEZ</h1>
    <!-- <a class="navbar-brand" href="{{ url_for('home.index') }}">ScrapEZ</a> -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul role="tablist" class="mr-auto nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('home.index') }}"><i class='ui home icon'></i>Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('videos.index') }}"><i class='ui video play icon'></i>Videos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('downloads.index') }}"><i class='ui download icon'></i>Downloads</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('chat.index') }}"><i class='ui keyboard icon'></i>Chat</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</div>

scrapez/ui/templates/videos.html
{% extends 'layout.html' %}

{% block js_assets %}
  <script src="{{ url_for('static', filename='js/video_events.js') }}"></script>
{% endblock %}

{% block body %}
  <style media="screen" type="text/css">
    #results .item {
      position: relative;
    }
    #results img {
      float: left;
    }
    #results .content {
      margin-left: 130px;
    }
  </style>
  <div class='ui segment'>
    <div class='ui input'>
      <input id='search' placeholder="Search for a video ..."></input>
    </div>
    <button class='ui button' id='query'><i class='ui search icon'></i>Search</button>
    </br></br>
  </div>
  <div class='ui segment'>
    <div id='results_header'>
      <div class='ui header'>Results</div>
      <p data-number=0 id='nresults'>No results found.</p>
    </div>
    <div id='loader' width="50%" class="ui icon message">
      <i class="notched circle loading icon"></i>
      <div class="content">
        <div class="header">
          Searching for videos ...
        </div>
        <p>We're looking on YouTube for some content.</p>
      </div>
    </div>
    <div id='results' class="ui padded celled list">
    </div>
  </div>
{% endblock %}